language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../mp2-lab3-Stack
  - make -j
  - ls
  - ./test/test_Stack
notifications:
  email: false
  